; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\Jorge Fernandez\Desktop\Sistemas Operativos I\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial15\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2592	DB	' Sistemas Operativos I - CEUTEC...                      '
	DB	' ', 00H
	ORG $+2
$SG2593	DB	' TF141 Iniciando...', 0aH, 00H
	ORG $+7
$SG2594	DB	' Inicializando Capa de Abstraccion de Hardware (HAL.lib)'
	DB	'...                           ', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	?hal_initialize@@YAHXZ:PROC			; hal_initialize
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
EXTRN	?DebugSetColor@@YAII@Z:PROC			; DebugSetColor
EXTRN	?DebugGotoXY@@YAXII@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScr@@YAXE@Z:PROC			; DebugClrScr
; Function compile flags: /Ogtpy
; File c:\documents and settings\jorge fernandez\desktop\sistemas operativos i\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial15\syscore\kernel\main.cpp
_TEXT	SEGMENT
_main	PROC

; 13   : 
; 14   : 	DebugClrScr (0x18);

	push	24					; 00000018H
	call	?DebugClrScr@@YAXE@Z			; DebugClrScr

; 15   : 
; 16   : 	DebugGotoXY (0,0);

	push	0
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 17   : 	DebugSetColor (0x70);

	push	112					; 00000070H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 18   : 	DebugPrintf (" Sistemas Operativos I - CEUTEC...                       ");

	push	OFFSET $SG2592
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 19   : 	DebugGotoXY (0,1);

	push	1
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 20   : 	DebugSetColor (0x19);

	push	25					; 00000019H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 21   : 	DebugPrintf (" TF141 Iniciando...\n");

	push	OFFSET $SG2593
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 22   : 
; 23   : 	DebugSetColor (0x70);

	push	112					; 00000070H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 24   : 	DebugGotoXY (0,24);

	push	24					; 00000018H
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 25   : 	DebugPrintf (" Inicializando Capa de Abstraccion de Hardware (HAL.lib)...                           ");

	push	OFFSET $SG2594
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 26   : 
; 27   : 	DebugSetColor (0x19);

	push	25					; 00000019H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 28   : 	DebugGotoXY (0,2);

	push	2
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY
	add	esp, 64					; 00000040H

; 29   : 
; 30   : 	hal_initialize ();

	call	?hal_initialize@@YAHXZ			; hal_initialize

; 31   : 
; 32   : //! uncomment to generate interrupt 0x15. This will call the default exception handler
; 33   : //	geninterrupt (0x15);
; 34   : 
; 35   : 	return 0;

	xor	eax, eax

; 36   : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
