; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\Jorge Fernandez\Desktop\Sistemas Operativos I\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial17\SysCore\Kernel\panic.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
_sickpc	DD	FLAT:$SG2629
_disc	DD	FLAT:$SG2631
_DATA	ENDS
CONST	SEGMENT
$SG2629	DB	'                                _______      ', 0aH, '  '
	DB	'                             |.-----.|    ', 0aH, '          '
	DB	'                     ||x . x||    ', 0aH, '                  '
	DB	'             ||_.-._||    ', 0aH, '                          '
	DB	'     `--)-(--`    ', 0aH, '                              __[='
	DB	'== o]___  ', 0aH, '                             |:::::::::::|'
	DB	'\ ', 0aH, '                             `-=========-`()', 0aH
	DB	'                                M. O. S.', 0aH, 0aH, 00H
	ORG $+4
$SG2631	DB	'An internal error was detected. The system has been halt'
	DB	'ed.', 0aH, 'Please restart your computer.', 0aH, 0aH, 00H
$SG2640	DB	'*** STOP: %s ', 0aH, 0aH, 00H
CONST	ENDS
PUBLIC	?kernel_panic@@YAXPBDZZ				; kernel_panic
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
EXTRN	?vsprintf@@YAHPADPBDPAE@Z:PROC			; vsprintf
EXTRN	?DebugPuts@@YAXPAD@Z:PROC			; DebugPuts
EXTRN	?DebugSetColor@@YAII@Z:PROC			; DebugSetColor
EXTRN	?DebugGotoXY@@YAXII@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScr@@YAXE@Z:PROC			; DebugClrScr
EXTRN	?disable@@YAXXZ:PROC				; disable
; Function compile flags: /Ogspy
; File c:\documents and settings\jorge fernandez\desktop\sistemas operativos i\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial17\syscore\kernel\panic.cpp
;	COMDAT ?kernel_panic@@YAXPBDZZ
_TEXT	SEGMENT
_buf$ = -1024						; size = 1024
_fmt$ = 8						; size = 4
?kernel_panic@@YAXPBDZZ PROC				; kernel_panic, COMDAT

; 27   : void _cdecl kernel_panic (const char* fmt, ...) {

	push	ebp
	mov	ebp, esp
	sub	esp, 1024				; 00000400H

; 28   : 
; 29   : 	disable ();

	call	?disable@@YAXXZ				; disable

; 30   : 
; 31   : 	DebugClrScr (0x13);

	push	19					; 00000013H
	call	?DebugClrScr@@YAXE@Z			; DebugClrScr

; 32   : 	DebugGotoXY (0,0);

	push	0
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 33   : 	DebugSetColor (0x17);

	push	23					; 00000017H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 34   : 
; 35   : 	DebugPuts (sickpc);

	push	DWORD PTR _sickpc
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 36   : 	DebugPuts (disc);

	push	DWORD PTR _disc
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 37   : 
; 38   : 	va_list		args;
; 39   : 
; 40   : 	char buf[1024];
; 41   : 
; 42   : 	va_start (args, fmt);
; 43   : 	vsprintf (buf, fmt, args);

	lea	eax, DWORD PTR _fmt$[ebp+4]
	push	eax
	push	DWORD PTR _fmt$[ebp]
	lea	eax, DWORD PTR _buf$[ebp]
	push	eax
	call	?vsprintf@@YAHPADPBDPAE@Z		; vsprintf

; 44   : 	va_end (args);
; 45   : 
; 46   : 	DebugPrintf ("*** STOP: %s \n\n", buf);

	lea	eax, DWORD PTR _buf$[ebp]
	push	eax
	push	OFFSET $SG2640
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 44					; 0000002cH
$LL2@kernel_pan:

; 47   : 
; 48   : 	for (;;);

	jmp	SHORT $LL2@kernel_pan
?kernel_panic@@YAXPBDZZ ENDP				; kernel_panic
_TEXT	ENDS
END
