; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\Jorge Fernandez\Desktop\Sistemas Operativos I\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial14\SysCore\Kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_0CD@IENPHOFN@?6?6Cargando?0?5por?5favor?5espere?4?4?4?5@ ; `string'
PUBLIC	??_C@_07CFAMGIEN@?6?$FL0x?$CFx?$FN?$AA@		; `string'
PUBLIC	??_C@_05HPJKAPFK@?6?$FL?$CFi?$FN?$AA@		; `string'
PUBLIC	??_C@_0CO@PPILHKCF@?6i?5numero?5de?5cuenta?5en?5hexadecim@ ; `string'
PUBLIC	??_C@_0CN@GDJLOONJ@?6i?5numero?5de?5cuenta?5?4?4?4?4?4?4?4?4?4?4?4?4@ ; `string'
PUBLIC	??_C@_0CO@MLNNAIEG@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ ; `string'
PUBLIC	??_C@_0CN@LPPLCDGO@?$HM?5?5?5?5TF141?532bit?5Kernel?5Ejecutan@ ; `string'
PUBLIC	??_C@_0CN@FMGOCDKO@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ ; `string'
PUBLIC	_main
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
EXTRN	?DebugSetColor@@YAII@Z:PROC			; DebugSetColor
EXTRN	?DebugGotoXY@@YAXII@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScr@@YAXG@Z:PROC			; DebugClrScr
;	COMDAT ??_C@_0CD@IENPHOFN@?6?6Cargando?0?5por?5favor?5espere?4?4?4?5@
; File c:\documents and settings\jorge fernandez\desktop\sistemas operativos i\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial14\syscore\kernel\main.cpp
CONST	SEGMENT
??_C@_0CD@IENPHOFN@?6?6Cargando?0?5por?5favor?5espere?4?4?4?5@ DB 0aH, 0aH
	DB	'Cargando, por favor espere... :)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07CFAMGIEN@?6?$FL0x?$CFx?$FN?$AA@
CONST	SEGMENT
??_C@_07CFAMGIEN@?6?$FL0x?$CFx?$FN?$AA@ DB 0aH, '[0x%x]', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_05HPJKAPFK@?6?$FL?$CFi?$FN?$AA@
CONST	SEGMENT
??_C@_05HPJKAPFK@?6?$FL?$CFi?$FN?$AA@ DB 0aH, '[%i]', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CO@PPILHKCF@?6i?5numero?5de?5cuenta?5en?5hexadecim@
CONST	SEGMENT
??_C@_0CO@PPILHKCF@?6i?5numero?5de?5cuenta?5en?5hexadecim@ DB 0aH, 'i num'
	DB	'ero de cuenta en hexadecimal ..........', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CN@GDJLOONJ@?6i?5numero?5de?5cuenta?5?4?4?4?4?4?4?4?4?4?4?4?4@
CONST	SEGMENT
??_C@_0CN@GDJLOONJ@?6i?5numero?5de?5cuenta?5?4?4?4?4?4?4?4?4?4?4?4?4@ DB 0aH
	DB	'i numero de cuenta ........................', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CO@MLNNAIEG@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@
CONST	SEGMENT
??_C@_0CO@MLNNAIEG@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ DB '+'
	DB	'-----------------------------------------+', 0aH, 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CN@LPPLCDGO@?$HM?5?5?5?5TF141?532bit?5Kernel?5Ejecutan@
CONST	SEGMENT
??_C@_0CN@LPPLCDGO@?$HM?5?5?5?5TF141?532bit?5Kernel?5Ejecutan@ DB '|    T'
	DB	'F141 32bit Kernel Ejecutandose      |', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CN@FMGOCDKO@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@
CONST	SEGMENT
??_C@_0CN@FMGOCDKO@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ DB '+'
	DB	'-----------------------------------------+', 0aH, 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 11   : 
; 12   : 	int i=0x1410FB2;
; 13   : 
; 14   : 	DebugClrScr (0x18);

	push	24					; 00000018H
	call	?DebugClrScr@@YAXG@Z			; DebugClrScr

; 15   : 
; 16   : 	DebugGotoXY (4,4);

	push	4
	push	4
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 17   : 	DebugSetColor (0x70);

	push	112					; 00000070H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 18   : 	DebugPrintf ("+-----------------------------------------+\n");

	push	OFFSET ??_C@_0CN@FMGOCDKO@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 19   : 	DebugPrintf ("|    TF141 32bit Kernel Ejecutandose      |\n");

	push	OFFSET ??_C@_0CN@LPPLCDGO@?$HM?5?5?5?5TF141?532bit?5Kernel?5Ejecutan@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 20   : 	DebugPrintf ("+-----------------------------------------+\n\n");

	push	OFFSET ??_C@_0CO@MLNNAIEG@?$CL?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 21   : 	DebugSetColor (0x12);

	push	18					; 00000012H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 22   : 
; 23   : 	DebugSetColor (0x12);

	push	18					; 00000012H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 24   : 	DebugPrintf ("\ni numero de cuenta ........................");

	push	OFFSET ??_C@_0CN@GDJLOONJ@?6i?5numero?5de?5cuenta?5?4?4?4?4?4?4?4?4?4?4?4?4@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 25   : 	DebugPrintf ("\ni numero de cuenta en hexadecimal ..........");

	push	OFFSET ??_C@_0CO@PPILHKCF@?6i?5numero?5de?5cuenta?5en?5hexadecim@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 26   : 
; 27   : 	DebugGotoXY (25,8);

	push	8
	push	25					; 00000019H
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 28   : 	DebugSetColor (0x1F);

	push	31					; 0000001fH
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 29   : 	DebugPrintf ("\n[%i]",i);

	push	21041074				; 01410fb2H
	push	OFFSET ??_C@_05HPJKAPFK@?6?$FL?$CFi?$FN?$AA@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 64					; 00000040H

; 30   : 	DebugPrintf ("\n[0x%x]",i);

	push	21041074				; 01410fb2H
	push	OFFSET ??_C@_07CFAMGIEN@?6?$FL0x?$CFx?$FN?$AA@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf

; 31   : 
; 32   : 	DebugGotoXY (4,16);

	push	16					; 00000010H
	push	4
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 33   : 	DebugSetColor (0x70);

	push	112					; 00000070H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 34   : 	DebugPrintf ("\n\nCargando, por favor espere... :)");

	push	OFFSET ??_C@_0CD@IENPHOFN@?6?6Cargando?0?5por?5favor?5espere?4?4?4?5@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 24					; 00000018H

; 35   : 
; 36   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
