; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\Jorge Fernandez\Desktop\Sistemas Operativos I\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial20\SysCore\FloppyDisk\flpydsk.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_BSS	SEGMENT
__CurrentDrive DB 01H DUP (?)
__FloppyDiskIRQ DB 01H DUP (?)
_BSS	ENDS
PUBLIC	?flpydsk_initialize_dma@@YAXXZ			; flpydsk_initialize_dma
EXTRN	?outportb@@YAXGE@Z:PROC				; outportb
; Function compile flags: /Ogtpy
; File c:\documents and settings\jorge fernandez\desktop\sistemas operativos i\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial20\syscore\floppydisk\flpydsk.cpp
_TEXT	SEGMENT
?flpydsk_initialize_dma@@YAXXZ PROC			; flpydsk_initialize_dma

; 203  : 
; 204  : 	outportb (0x0a,0x06);	//mask dma channel 2

	push	6
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb

; 205  : 	outportb (0xd8,0xff);	//reset master flip-flop

	push	255					; 000000ffH
	push	216					; 000000d8H
	call	?outportb@@YAXGE@Z			; outportb

; 206  : 	outportb (0x04, 0);     //address=0x1000 

	push	0
	push	4
	call	?outportb@@YAXGE@Z			; outportb

; 207  : 	outportb (0x04, 0x10);

	push	16					; 00000010H
	push	4
	call	?outportb@@YAXGE@Z			; outportb

; 208  : 	outportb (0xd8, 0xff);  //reset master flip-flop

	push	255					; 000000ffH
	push	216					; 000000d8H
	call	?outportb@@YAXGE@Z			; outportb

; 209  : 	outportb (0x05, 0xff);  //count to 0x23ff (number of bytes in a 3.5" floppy disk track)

	push	255					; 000000ffH
	push	5
	call	?outportb@@YAXGE@Z			; outportb

; 210  : 	outportb (0x05, 0x23);

	push	35					; 00000023H
	push	5
	call	?outportb@@YAXGE@Z			; outportb

; 211  : 	outportb (0x80, 0);     //external page register = 0

	push	0
	push	128					; 00000080H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 64					; 00000040H

; 212  : 	outportb (0x0a, 0x02);  //unmask dma channel 2

	push	2
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 213  : }

	ret	0
?flpydsk_initialize_dma@@YAXXZ ENDP			; flpydsk_initialize_dma
_TEXT	ENDS
PUBLIC	?flpydsk_dma_read@@YAXXZ			; flpydsk_dma_read
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_dma_read@@YAXXZ PROC				; flpydsk_dma_read

; 217  : 
; 218  : 	outportb (0x0a, 0x06); //mask dma channel 2

	push	6
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb

; 219  : 	outportb (0x0b, 0x56); //single transfer, address increment, autoinit, read, channel 2

	push	86					; 00000056H
	push	11					; 0000000bH
	call	?outportb@@YAXGE@Z			; outportb

; 220  : 	outportb (0x0a, 0x02); //unmask dma channel 2

	push	2
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 24					; 00000018H

; 221  : }

	ret	0
?flpydsk_dma_read@@YAXXZ ENDP				; flpydsk_dma_read
_TEXT	ENDS
PUBLIC	?flpydsk_dma_write@@YAXXZ			; flpydsk_dma_write
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_dma_write@@YAXXZ PROC				; flpydsk_dma_write

; 225  : 
; 226  : 	outportb (0x0a, 0x06); //mask dma channel 2

	push	6
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb

; 227  : 	outportb (0x0b, 0x5a); //single transfer, address increment, autoinit, write, channel 2

	push	90					; 0000005aH
	push	11					; 0000000bH
	call	?outportb@@YAXGE@Z			; outportb

; 228  : 	outportb (0x0a, 0x02); //unmask dma channel 2

	push	2
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 24					; 00000018H

; 229  : }

	ret	0
?flpydsk_dma_write@@YAXXZ ENDP				; flpydsk_dma_write
_TEXT	ENDS
PUBLIC	?flpydsk_read_status@@YAEXZ			; flpydsk_read_status
EXTRN	?inportb@@YAEG@Z:PROC				; inportb
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_read_status@@YAEXZ PROC			; flpydsk_read_status

; 237  : 
; 238  : 	//! just return main status register
; 239  : 	return inportb (FLPYDSK_MSR);

	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4

; 240  : }

	ret	0
?flpydsk_read_status@@YAEXZ ENDP			; flpydsk_read_status
_TEXT	ENDS
PUBLIC	?flpydsk_write_dor@@YAXE@Z			; flpydsk_write_dor
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_val$ = 8						; size = 1
?flpydsk_write_dor@@YAXE@Z PROC				; flpydsk_write_dor

; 244  : 
; 245  : 	//! write the digital output register
; 246  : 	outportb (FLPYDSK_DOR, val);

	mov	eax, DWORD PTR _val$[esp-4]
	push	eax
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 247  : }

	ret	0
?flpydsk_write_dor@@YAXE@Z ENDP				; flpydsk_write_dor
_TEXT	ENDS
PUBLIC	?flpydsk_send_command@@YAXE@Z			; flpydsk_send_command
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_cmd$ = 8						; size = 1
?flpydsk_send_command@@YAXE@Z PROC			; flpydsk_send_command

; 250  : void flpydsk_send_command (uint8_t cmd) {

	push	esi

; 251  : 
; 252  : 	//! wait until data register is ready. We send commands to the data register
; 253  : 	for (int i = 0; i < 500; i++ )

	xor	esi, esi
$LL4@flpydsk_se:

; 254  : 		if ( flpydsk_read_status () & FLPYDSK_MSR_MASK_DATAREG )

	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN10@flpydsk_se

; 251  : 
; 252  : 	//! wait until data register is ready. We send commands to the data register
; 253  : 	for (int i = 0; i < 500; i++ )

	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL4@flpydsk_se
	pop	esi

; 256  : }

	ret	0
$LN10@flpydsk_se:

; 255  : 			return outportb (FLPYDSK_FIFO, cmd);

	mov	eax, DWORD PTR _cmd$[esp]
	push	eax
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
	pop	esi

; 256  : }

	ret	0
?flpydsk_send_command@@YAXE@Z ENDP			; flpydsk_send_command
_TEXT	ENDS
PUBLIC	?flpydsk_read_data@@YAEXZ			; flpydsk_read_data
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_read_data@@YAEXZ PROC				; flpydsk_read_data

; 259  : uint8_t flpydsk_read_data () {

	push	esi

; 260  : 
; 261  : 	//! same as above function but returns data register for reading
; 262  : 	for (int i = 0; i < 500; i++ )

	xor	esi, esi
$LL4@flpydsk_re:

; 263  : 		if ( flpydsk_read_status () & FLPYDSK_MSR_MASK_DATAREG )

	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN10@flpydsk_re

; 260  : 
; 261  : 	//! same as above function but returns data register for reading
; 262  : 	for (int i = 0; i < 500; i++ )

	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL4@flpydsk_re

; 265  : 
; 266  : 	return 0;

	xor	al, al
	pop	esi

; 267  : }

	ret	0
$LN10@flpydsk_re:

; 264  : 			return inportb (FLPYDSK_FIFO);

	push	1013					; 000003f5H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	pop	esi

; 267  : }

	ret	0
?flpydsk_read_data@@YAEXZ ENDP				; flpydsk_read_data
_TEXT	ENDS
PUBLIC	?flpydsk_write_ccr@@YAXE@Z			; flpydsk_write_ccr
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_val$ = 8						; size = 1
?flpydsk_write_ccr@@YAXE@Z PROC				; flpydsk_write_ccr

; 271  : 
; 272  : 	//! write the configuation control
; 273  : 	outportb (FLPYDSK_CTRL, val);

	mov	eax, DWORD PTR _val$[esp-4]
	push	eax
	push	1015					; 000003f7H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 274  : }

	ret	0
?flpydsk_write_ccr@@YAXE@Z ENDP				; flpydsk_write_ccr
_TEXT	ENDS
PUBLIC	?flpydsk_wait_irq@@YAXXZ			; flpydsk_wait_irq
; Function compile flags: /Ogtpy
;	COMDAT ?flpydsk_wait_irq@@YAXXZ
_TEXT	SEGMENT
?flpydsk_wait_irq@@YAXXZ PROC				; flpydsk_wait_irq, COMDAT

; 281  : inline void flpydsk_wait_irq () {

$LL2@flpydsk_wa:

; 282  : 
; 283  : 	//! wait for irq to fire
; 284  : 	while ( _FloppyDiskIRQ == 0)

	mov	al, BYTE PTR __FloppyDiskIRQ
	test	al, al
	je	SHORT $LL2@flpydsk_wa

; 285  : 		;
; 286  : 	_FloppyDiskIRQ = 0;

	mov	BYTE PTR __FloppyDiskIRQ, 0

; 287  : }

	ret	0
?flpydsk_wait_irq@@YAXXZ ENDP				; flpydsk_wait_irq
_TEXT	ENDS
PUBLIC	?i86_flpy_irq@@YAXXZ				; i86_flpy_irq
EXTRN	?interruptdone@@YAXI@Z:PROC			; interruptdone
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?i86_flpy_irq@@YAXXZ PROC				; i86_flpy_irq

; 291  : void _cdecl i86_flpy_irq () {

	push	ebx
	push	esi
	push	edi

; 292  : 
; 293  : 	_asm add esp, 12

	add	esp, 12					; 0000000cH

; 294  : 	_asm pushad

	pushad

; 295  : 	_asm cli

	cli

; 296  : 
; 297  : 	//! irq fired
; 298  : 	_FloppyDiskIRQ = 1;
; 299  : 
; 300  : 	//! tell hal we are done
; 301  : 	interruptdone( FLOPPY_IRQ );

	push	6
	mov	BYTE PTR __FloppyDiskIRQ, 1
	call	?interruptdone@@YAXI@Z			; interruptdone
	add	esp, 4

; 302  : 
; 303  : 	_asm sti

	sti

; 304  : 	_asm popad

	popad

; 305  : 	_asm iretd

	iretd

; 306  : }

	pop	edi
	pop	esi
	pop	ebx
	ret	0
?i86_flpy_irq@@YAXXZ ENDP				; i86_flpy_irq
_TEXT	ENDS
PUBLIC	?flpydsk_check_int@@YAXPAI0@Z			; flpydsk_check_int
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_st0$ = 8						; size = 4
_cyl$ = 12						; size = 4
?flpydsk_check_int@@YAXPAI0@Z PROC			; flpydsk_check_int

; 313  : void flpydsk_check_int (uint32_t* st0, uint32_t* cyl) {

	push	esi

; 314  : 
; 315  : 	flpydsk_send_command (FDC_CMD_CHECK_INT);

	xor	esi, esi
$LL6@flpydsk_ch:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN30@flpydsk_ch
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL6@flpydsk_ch

; 318  : 	*cyl = flpydsk_read_data ();

	jmp	SHORT $LN4@flpydsk_ch
$LN30@flpydsk_ch:

; 314  : 
; 315  : 	flpydsk_send_command (FDC_CMD_CHECK_INT);

	push	8
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN4@flpydsk_ch:

; 316  : 
; 317  : 	*st0 = flpydsk_read_data ();

	xor	esi, esi
$LL14@flpydsk_ch:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN31@flpydsk_ch
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL14@flpydsk_ch
	xor	al, al
$LN15@flpydsk_ch:
	mov	ecx, DWORD PTR _st0$[esp]
	movzx	eax, al
	mov	DWORD PTR [ecx], eax

; 318  : 	*cyl = flpydsk_read_data ();

	xor	esi, esi
	npad	9
$LL22@flpydsk_ch:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN32@flpydsk_ch
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL22@flpydsk_ch
	mov	edx, DWORD PTR _cyl$[esp]
	xor	al, al
	movzx	ecx, al
	mov	DWORD PTR [edx], ecx
	pop	esi

; 319  : }

	ret	0
$LN31@flpydsk_ch:

; 316  : 
; 317  : 	*st0 = flpydsk_read_data ();

	push	1013					; 000003f5H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	jmp	SHORT $LN15@flpydsk_ch
$LN32@flpydsk_ch:

; 318  : 	*cyl = flpydsk_read_data ();

	push	1013					; 000003f5H
	call	?inportb@@YAEG@Z			; inportb
	movzx	edx, al
	mov	eax, DWORD PTR _cyl$[esp+4]
	add	esp, 4
	mov	DWORD PTR [eax], edx
	pop	esi

; 319  : }

	ret	0
?flpydsk_check_int@@YAXPAI0@Z ENDP			; flpydsk_check_int
_TEXT	ENDS
PUBLIC	?flpydsk_control_motor@@YAX_N@Z			; flpydsk_control_motor
EXTRN	?sleep@@YAXH@Z:PROC				; sleep
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_b$ = 8							; size = 1
?flpydsk_control_motor@@YAX_N@Z PROC			; flpydsk_control_motor

; 323  : 
; 324  : 	//! sanity check: invalid drive
; 325  : 	if (_CurrentDrive > 3)

	mov	al, BYTE PTR __CurrentDrive
	cmp	al, 3
	ja	SHORT $LN10@flpydsk_co

; 326  : 		return;
; 327  : 
; 328  : 	uint32_t motor = 0;
; 329  : 
; 330  : 	//! select the correct mask based on current drive
; 331  : 	switch (_CurrentDrive) {

	movzx	ecx, al
	xor	edx, edx
	cmp	ecx, 3
	ja	SHORT $LN7@flpydsk_co
	jmp	DWORD PTR $LN18@flpydsk_co[ecx*4]
$LN6@flpydsk_co:

; 332  : 
; 333  : 		case 0:
; 334  : 			motor = FLPYDSK_DOR_MASK_DRIVE0_MOTOR;

	mov	edx, 16					; 00000010H

; 335  : 			break;

	jmp	SHORT $LN7@flpydsk_co
$LN5@flpydsk_co:

; 336  : 		case 1:
; 337  : 			motor = FLPYDSK_DOR_MASK_DRIVE1_MOTOR;

	mov	edx, 32					; 00000020H

; 338  : 			break;

	jmp	SHORT $LN7@flpydsk_co
$LN4@flpydsk_co:

; 339  : 		case 2:
; 340  : 			motor = FLPYDSK_DOR_MASK_DRIVE2_MOTOR;

	mov	edx, 64					; 00000040H

; 341  : 			break;

	jmp	SHORT $LN7@flpydsk_co
$LN3@flpydsk_co:

; 342  : 		case 3:
; 343  : 			motor = FLPYDSK_DOR_MASK_DRIVE3_MOTOR;

	mov	edx, 128				; 00000080H
$LN7@flpydsk_co:

; 344  : 			break;
; 345  : 	}
; 346  : 
; 347  : 	//! turn on or off the motor of that drive
; 348  : 	if (b)

	cmp	BYTE PTR _b$[esp-4], 0
	je	SHORT $LN2@flpydsk_co

; 349  : 		flpydsk_write_dor (_CurrentDrive | motor | FLPYDSK_DOR_MASK_RESET | FLPYDSK_DOR_MASK_DMA);

	or	al, dl
	or	al, 12					; 0000000cH
	movzx	eax, al
	push	eax

; 350  : 	else

	jmp	SHORT $LN17@flpydsk_co
$LN2@flpydsk_co:

; 351  : 		flpydsk_write_dor (FLPYDSK_DOR_MASK_RESET);

	push	4
$LN17@flpydsk_co:
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 352  : 
; 353  : 	//! in all cases; wait a little bit for the motor to spin up/turn off
; 354  : 	sleep (20);

	mov	DWORD PTR _b$[esp-4], 20		; 00000014H
	jmp	?sleep@@YAXH@Z				; sleep
$LN10@flpydsk_co:

; 355  : }

	ret	0
	npad	2
$LN18@flpydsk_co:
	DD	$LN6@flpydsk_co
	DD	$LN5@flpydsk_co
	DD	$LN4@flpydsk_co
	DD	$LN3@flpydsk_co
?flpydsk_control_motor@@YAX_N@Z ENDP			; flpydsk_control_motor
_TEXT	ENDS
PUBLIC	?flpydsk_drive_data@@YAXIII_N@Z			; flpydsk_drive_data
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_stepr$ = 8						; size = 4
_loadt$ = 12						; size = 4
_unloadt$ = 16						; size = 4
_dma$ = 20						; size = 1
?flpydsk_drive_data@@YAXIII_N@Z PROC			; flpydsk_drive_data

; 358  : void flpydsk_drive_data (uint32_t stepr, uint32_t loadt, uint32_t unloadt, bool dma ) {

	push	esi
	push	edi

; 359  : 
; 360  : 	uint32_t data = 0;
; 361  : 
; 362  : 	//! send command
; 363  : 	flpydsk_send_command (FDC_CMD_SPECIFY);

	xor	esi, esi
$LL6@flpydsk_dr:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN30@flpydsk_dr
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL6@flpydsk_dr

; 367  : 		flpydsk_send_command (data);

	jmp	SHORT $LN4@flpydsk_dr
$LN30@flpydsk_dr:

; 359  : 
; 360  : 	uint32_t data = 0;
; 361  : 
; 362  : 	//! send command
; 363  : 	flpydsk_send_command (FDC_CMD_SPECIFY);

	push	3
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN4@flpydsk_dr:

; 364  : 	data = ( (stepr & 0xf) << 4) | (unloadt & 0xf);

	mov	esi, DWORD PTR _stepr$[esp+4]
	mov	eax, DWORD PTR _unloadt$[esp+4]
	and	esi, 15					; 0000000fH
	shl	esi, 4
	and	eax, 15					; 0000000fH
	or	esi, eax

; 365  : 		flpydsk_send_command (data);

	xor	edi, edi
$LL14@flpydsk_dr:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN31@flpydsk_dr
	inc	edi
	cmp	edi, 500				; 000001f4H
	jl	SHORT $LL14@flpydsk_dr

; 367  : 		flpydsk_send_command (data);

	jmp	SHORT $LN12@flpydsk_dr
$LN31@flpydsk_dr:

; 365  : 		flpydsk_send_command (data);

	push	esi
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN12@flpydsk_dr:

; 366  : 	data = (loadt) << 1 | (dma==false) ? 0 : 1;

	mov	edx, DWORD PTR _loadt$[esp+4]
	xor	ecx, ecx
	cmp	BYTE PTR _dma$[esp+4], cl
	lea	eax, DWORD PTR [edx+edx]
	sete	cl
	or	ecx, eax
	neg	ecx
	sbb	ecx, ecx
	lea	edi, DWORD PTR [ecx+1]

; 367  : 		flpydsk_send_command (data);

	xor	esi, esi
	npad	7
$LL22@flpydsk_dr:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN32@flpydsk_dr
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL22@flpydsk_dr
	pop	edi
	pop	esi

; 368  : }

	ret	0
$LN32@flpydsk_dr:

; 367  : 		flpydsk_send_command (data);

	push	edi
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
	pop	edi
	pop	esi

; 368  : }

	ret	0
?flpydsk_drive_data@@YAXIII_N@Z ENDP			; flpydsk_drive_data
_TEXT	ENDS
PUBLIC	?flpydsk_calibrate@@YAHI@Z			; flpydsk_calibrate
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_st0$ = -4						; size = 4
tv226 = 8						; size = 4
_cyl$ = 8						; size = 4
_drive$ = 8						; size = 4
?flpydsk_calibrate@@YAHI@Z PROC				; flpydsk_calibrate

; 371  : int flpydsk_calibrate (uint32_t drive) {

	push	ecx
	push	ebp

; 372  : 
; 373  : 	uint32_t st0, cyl;
; 374  : 
; 375  : 	if (drive >= 4)

	mov	ebp, DWORD PTR _drive$[esp+4]
	cmp	ebp, 4
	jb	SHORT $LN5@flpydsk_ca

; 376  : 		return -2;

	mov	eax, -2					; fffffffeH
	pop	ebp

; 399  : }

	pop	ecx
	ret	0
$LN5@flpydsk_ca:

; 377  : 
; 378  : 	//! turn on the motor
; 379  : 	flpydsk_control_motor (true);

	mov	al, BYTE PTR __CurrentDrive
	cmp	al, 3
	ja	SHORT $LN17@flpydsk_ca
	movzx	edx, al
	xor	ecx, ecx
	cmp	edx, 3
	ja	SHORT $LN14@flpydsk_ca
	jmp	DWORD PTR $LN89@flpydsk_ca[edx*4]
$LN13@flpydsk_ca:
	mov	ecx, 16					; 00000010H
	jmp	SHORT $LN14@flpydsk_ca
$LN12@flpydsk_ca:
	mov	ecx, 32					; 00000020H
	jmp	SHORT $LN14@flpydsk_ca
$LN11@flpydsk_ca:
	mov	ecx, 64					; 00000040H
	jmp	SHORT $LN14@flpydsk_ca
$LN10@flpydsk_ca:
	mov	ecx, 128				; 00000080H
$LN14@flpydsk_ca:
	or	al, cl
	or	al, 12					; 0000000cH
	movzx	eax, al
	push	eax
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	push	20					; 00000014H
	call	?sleep@@YAXH@Z				; sleep
	add	esp, 12					; 0000000cH
$LN17@flpydsk_ca:

; 380  : 
; 381  : 	for (int i = 0; i < 10; i++) {

	push	edi
	xor	edi, edi
	push	esi
	npad	9
$LL4@flpydsk_ca:

; 382  : 
; 383  : 		//! send command
; 384  : 		flpydsk_send_command ( FDC_CMD_CALIBRATE );

	xor	esi, esi
$LL26@flpydsk_ca:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN77@flpydsk_ca
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL26@flpydsk_ca

; 388  : 
; 389  : 		//! did we fine cylinder 0? if so, we are done
; 390  : 		if (!cyl) {

	jmp	SHORT $LN24@flpydsk_ca
$LN77@flpydsk_ca:

; 382  : 
; 383  : 		//! send command
; 384  : 		flpydsk_send_command ( FDC_CMD_CALIBRATE );

	push	7
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN24@flpydsk_ca:

; 385  : 		flpydsk_send_command ( drive );

	xor	esi, esi
	npad	1
$LL34@flpydsk_ca:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN78@flpydsk_ca
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL34@flpydsk_ca

; 388  : 
; 389  : 		//! did we fine cylinder 0? if so, we are done
; 390  : 		if (!cyl) {

	jmp	SHORT $LL40@flpydsk_ca
$LN78@flpydsk_ca:

; 385  : 		flpydsk_send_command ( drive );

	push	ebp
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
	npad	6

; 386  : 		flpydsk_wait_irq ();

$LL40@flpydsk_ca:
	mov	cl, BYTE PTR __FloppyDiskIRQ
	test	cl, cl
	je	SHORT $LL40@flpydsk_ca

; 387  : 		flpydsk_check_int ( &st0, &cyl);

	lea	edx, DWORD PTR _cyl$[esp+12]
	push	edx
	lea	eax, DWORD PTR _st0$[esp+20]
	push	eax
	mov	BYTE PTR __FloppyDiskIRQ, 0
	call	?flpydsk_check_int@@YAXPAI0@Z		; flpydsk_check_int
	add	esp, 8

; 388  : 
; 389  : 		//! did we fine cylinder 0? if so, we are done
; 390  : 		if (!cyl) {

	cmp	DWORD PTR _cyl$[esp+12], 0
	je	SHORT $LN79@flpydsk_ca

; 380  : 
; 381  : 	for (int i = 0; i < 10; i++) {

	inc	edi
	cmp	edi, 10					; 0000000aH
	jl	$LL4@flpydsk_ca

; 394  : 		}
; 395  : 	}
; 396  : 
; 397  : 	flpydsk_control_motor (false);

	mov	al, BYTE PTR __CurrentDrive
	cmp	al, 3
	ja	SHORT $LN67@flpydsk_ca
	push	4
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	push	20					; 00000014H
	call	?sleep@@YAXH@Z				; sleep
	add	esp, 12					; 0000000cH
$LN67@flpydsk_ca:

; 398  : 	return -1;

	pop	esi
	pop	edi
	or	eax, -1
	pop	ebp

; 399  : }

	pop	ecx
	ret	0
$LN79@flpydsk_ca:

; 391  : 
; 392  : 			flpydsk_control_motor (false);

	mov	al, BYTE PTR __CurrentDrive
	cmp	al, 3
	ja	SHORT $LN52@flpydsk_ca
	push	4
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	push	20					; 00000014H
	call	?sleep@@YAXH@Z				; sleep
	add	esp, 12					; 0000000cH
$LN52@flpydsk_ca:

; 393  : 			return 0;

	pop	esi
	pop	edi
	xor	eax, eax
	pop	ebp

; 399  : }

	pop	ecx
	ret	0
	npad	3
$LN89@flpydsk_ca:
	DD	$LN13@flpydsk_ca
	DD	$LN12@flpydsk_ca
	DD	$LN11@flpydsk_ca
	DD	$LN10@flpydsk_ca
?flpydsk_calibrate@@YAHI@Z ENDP				; flpydsk_calibrate
_TEXT	ENDS
PUBLIC	?flpydsk_disable_controller@@YAXXZ		; flpydsk_disable_controller
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_disable_controller@@YAXXZ PROC			; flpydsk_disable_controller

; 403  : 
; 404  : 	flpydsk_write_dor (0);

	push	0
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 405  : }

	ret	0
?flpydsk_disable_controller@@YAXXZ ENDP			; flpydsk_disable_controller
_TEXT	ENDS
PUBLIC	?flpydsk_enable_controller@@YAXXZ		; flpydsk_enable_controller
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_enable_controller@@YAXXZ PROC			; flpydsk_enable_controller

; 409  : 
; 410  : 	flpydsk_write_dor ( FLPYDSK_DOR_MASK_RESET | FLPYDSK_DOR_MASK_DMA);

	push	12					; 0000000cH
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8

; 411  : }

	ret	0
?flpydsk_enable_controller@@YAXXZ ENDP			; flpydsk_enable_controller
_TEXT	ENDS
PUBLIC	?flpydsk_reset@@YAXXZ				; flpydsk_reset
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_cyl$ = -8						; size = 4
_st0$ = -4						; size = 4
?flpydsk_reset@@YAXXZ PROC				; flpydsk_reset

; 414  : void flpydsk_reset () {

	sub	esp, 8

; 415  : 
; 416  : 	uint32_t st0, cyl;
; 417  : 
; 418  : 	//! reset the controller
; 419  : 	flpydsk_disable_controller ();

	push	0
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb

; 420  : 	flpydsk_enable_controller ();

	push	12					; 0000000cH
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 16					; 00000010H
	npad	2

; 421  : 	flpydsk_wait_irq ();

$LL15@flpydsk_re@2:
	mov	al, BYTE PTR __FloppyDiskIRQ
	test	al, al
	je	SHORT $LL15@flpydsk_re@2
	push	esi
	mov	BYTE PTR __FloppyDiskIRQ, 0
	mov	esi, 4
$LL3@flpydsk_re@2:

; 422  : 
; 423  : 	//! send CHECK_INT/SENSE INTERRUPT command to all drives
; 424  : 	for (int i=0; i<4; i++)
; 425  : 		flpydsk_check_int (&st0,&cyl);

	lea	ecx, DWORD PTR _cyl$[esp+12]
	push	ecx
	lea	edx, DWORD PTR _st0$[esp+16]
	push	edx
	call	?flpydsk_check_int@@YAXPAI0@Z		; flpydsk_check_int
	add	esp, 8
	dec	esi
	jne	SHORT $LL3@flpydsk_re@2

; 426  : 
; 427  : 	//! transfer speed 500kb/s
; 428  : 	flpydsk_write_ccr (0);

	push	esi
	push	1015					; 000003f7H
	call	?outportb@@YAXGE@Z			; outportb

; 429  : 
; 430  : 	//! pass mechanical drive info. steprate=3ms, unload time=240ms, load time=16ms
; 431  : 	flpydsk_drive_data (3,16,240,true);

	push	1
	push	240					; 000000f0H
	push	16					; 00000010H
	push	3
	call	?flpydsk_drive_data@@YAXIII_N@Z		; flpydsk_drive_data

; 432  : 
; 433  : 	//! calibrate the disk
; 434  : 	flpydsk_calibrate ( _CurrentDrive );

	movzx	eax, BYTE PTR __CurrentDrive
	push	eax
	call	?flpydsk_calibrate@@YAHI@Z		; flpydsk_calibrate
	add	esp, 28					; 0000001cH
	pop	esi

; 435  : }

	add	esp, 8
	ret	0
?flpydsk_reset@@YAXXZ ENDP				; flpydsk_reset
_TEXT	ENDS
PUBLIC	?flpydsk_read_sector_imp@@YAXEEE@Z		; flpydsk_read_sector_imp
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_head$ = 8						; size = 1
$T3144 = 8						; size = 1
_st0$ = 8						; size = 4
_track$ = 12						; size = 1
_sector$ = 16						; size = 1
_cyl$ = 16						; size = 4
?flpydsk_read_sector_imp@@YAXEEE@Z PROC			; flpydsk_read_sector_imp

; 438  : void flpydsk_read_sector_imp (uint8_t head, uint8_t track, uint8_t sector) {

	push	esi
	push	edi

; 439  : 
; 440  : 	uint32_t st0, cyl;
; 441  : 
; 442  : 	//! set the DMA for read transfer
; 443  : 	flpydsk_dma_read ();

	push	6
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb
	push	86					; 00000056H
	push	11					; 0000000bH
	call	?outportb@@YAXGE@Z			; outportb
	push	2
	push	10					; 0000000aH
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 24					; 00000018H

; 444  : 
; 445  : 	//! read in a sector
; 446  : 	flpydsk_send_command (
; 447  : 				FDC_CMD_READ_SECT | FDC_CMD_EXT_MULTITRACK | FDC_CMD_EXT_SKIP | FDC_CMD_EXT_DENSITY);

	xor	esi, esi
$LL13@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN106@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL13@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN11@flpydsk_re@3
$LN106@flpydsk_re@3:

; 444  : 
; 445  : 	//! read in a sector
; 446  : 	flpydsk_send_command (
; 447  : 				FDC_CMD_READ_SECT | FDC_CMD_EXT_MULTITRACK | FDC_CMD_EXT_SKIP | FDC_CMD_EXT_DENSITY);

	push	230					; 000000e6H
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN11@flpydsk_re@3:

; 448  : 	flpydsk_send_command ( head << 2 | _CurrentDrive );

	push	ebx
	mov	ebx, DWORD PTR _head$[esp+8]
	mov	al, bl
	add	al, al
	add	al, al
	or	al, BYTE PTR __CurrentDrive
	xor	esi, esi
	mov	BYTE PTR $T3144[esp+8], al
	npad	9
$LL21@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN107@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL21@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN19@flpydsk_re@3
$LN107@flpydsk_re@3:

; 448  : 	flpydsk_send_command ( head << 2 | _CurrentDrive );

	mov	ecx, DWORD PTR $T3144[esp+8]
	push	ecx
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN19@flpydsk_re@3:

; 449  : 	flpydsk_send_command ( track);

	xor	esi, esi
$LL29@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN108@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL29@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN27@flpydsk_re@3
$LN108@flpydsk_re@3:

; 449  : 	flpydsk_send_command ( track);

	mov	edx, DWORD PTR _track$[esp+8]
	push	edx
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN27@flpydsk_re@3:

; 450  : 	flpydsk_send_command ( head);

	xor	esi, esi
$LL37@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN109@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL37@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN35@flpydsk_re@3
$LN109@flpydsk_re@3:

; 450  : 	flpydsk_send_command ( head);

	push	ebx
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN35@flpydsk_re@3:

; 451  : 	flpydsk_send_command ( sector);

	xor	esi, esi
	pop	ebx
	npad	3
$LL45@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN110@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL45@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN43@flpydsk_re@3
$LN110@flpydsk_re@3:

; 451  : 	flpydsk_send_command ( sector);

	mov	eax, DWORD PTR _sector$[esp+4]
	push	eax
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN43@flpydsk_re@3:

; 452  : 	flpydsk_send_command ( FLPYDSK_SECTOR_DTL_512 );

	xor	esi, esi
$LL53@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN111@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL53@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN51@flpydsk_re@3
$LN111@flpydsk_re@3:

; 452  : 	flpydsk_send_command ( FLPYDSK_SECTOR_DTL_512 );

	push	2
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN51@flpydsk_re@3:

; 453  : 	flpydsk_send_command ( ( ( sector + 1 ) >= FLPY_SECTORS_PER_TRACK ) ? FLPY_SECTORS_PER_TRACK : sector + 1 );

	movzx	eax, BYTE PTR _sector$[esp+4]
	inc	eax
	mov	edi, 18					; 00000012H
	cmp	eax, 18					; 00000012H
	jge	SHORT $LN7@flpydsk_re@3
	mov	edi, eax
$LN7@flpydsk_re@3:
	xor	esi, esi
	npad	1
$LL61@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN112@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL61@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN59@flpydsk_re@3
$LN112@flpydsk_re@3:

; 453  : 	flpydsk_send_command ( ( ( sector + 1 ) >= FLPY_SECTORS_PER_TRACK ) ? FLPY_SECTORS_PER_TRACK : sector + 1 );

	push	edi
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN59@flpydsk_re@3:

; 454  : 	flpydsk_send_command ( FLPYDSK_GAP3_LENGTH_3_5 );

	xor	esi, esi
	npad	4
$LL69@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN113@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL69@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LN67@flpydsk_re@3
$LN113@flpydsk_re@3:

; 454  : 	flpydsk_send_command ( FLPYDSK_GAP3_LENGTH_3_5 );

	push	27					; 0000001bH
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN67@flpydsk_re@3:

; 455  : 	flpydsk_send_command ( 0xff );

	xor	esi, esi
	npad	3
$LL77@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN114@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL77@flpydsk_re@3

; 462  : 		flpydsk_read_data ();

	jmp	SHORT $LL83@flpydsk_re@3
$LN114@flpydsk_re@3:

; 455  : 	flpydsk_send_command ( 0xff );

	push	255					; 000000ffH
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
	npad	2

; 456  : 
; 457  : 	//! wait for irq
; 458  : 	flpydsk_wait_irq ();

$LL83@flpydsk_re@3:
	mov	cl, BYTE PTR __FloppyDiskIRQ
	test	cl, cl
	je	SHORT $LL83@flpydsk_re@3
	mov	BYTE PTR __FloppyDiskIRQ, 0
	mov	edi, 7
	npad	10
$LL3@flpydsk_re@3:

; 462  : 		flpydsk_read_data ();

	xor	esi, esi
$LL89@flpydsk_re@3:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN115@flpydsk_re@3
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL89@flpydsk_re@3
	jmp	SHORT $LN2@flpydsk_re@3
$LN115@flpydsk_re@3:
	push	1013					; 000003f5H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
$LN2@flpydsk_re@3:

; 459  : 
; 460  : 	//! read status info
; 461  : 	for (int j=0; j<7; j++)

	dec	edi
	jne	SHORT $LL3@flpydsk_re@3

; 463  : 
; 464  : 	//! let FDC know we handled interrupt
; 465  : 	flpydsk_check_int (&st0,&cyl);

	lea	edx, DWORD PTR _cyl$[esp+4]
	push	edx
	lea	eax, DWORD PTR _st0$[esp+8]
	push	eax
	call	?flpydsk_check_int@@YAXPAI0@Z		; flpydsk_check_int
	add	esp, 8
	pop	edi
	pop	esi

; 466  : }

	ret	0
?flpydsk_read_sector_imp@@YAXEEE@Z ENDP			; flpydsk_read_sector_imp
_TEXT	ENDS
PUBLIC	?flpydsk_seek@@YAHII@Z				; flpydsk_seek
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
$T3324 = -12						; size = 1
_cyl0$ = -8						; size = 4
_st0$ = -4						; size = 4
_cyl$ = 8						; size = 4
_head$ = 12						; size = 4
?flpydsk_seek@@YAHII@Z PROC				; flpydsk_seek

; 469  : int flpydsk_seek ( uint32_t cyl, uint32_t head ) {

	sub	esp, 12					; 0000000cH

; 470  : 
; 471  : 	uint32_t st0, cyl0;
; 472  : 
; 473  : 	if (_CurrentDrive >= 4)

	cmp	BYTE PTR __CurrentDrive, 4
	jb	SHORT $LN5@flpydsk_se@2

; 474  : 		return -1;

	or	eax, -1

; 493  : }

	add	esp, 12					; 0000000cH
	ret	0
$LN5@flpydsk_se@2:
	push	ebx

; 475  : 
; 476  : 	for (int i = 0; i < 10; i++ ) {

	mov	bl, BYTE PTR _head$[esp+12]
	push	ebp
	mov	ebp, DWORD PTR _cyl$[esp+16]
	push	edi
	add	bl, bl
	xor	edi, edi
	add	bl, bl
	push	esi
	npad	11
$LL51@flpydsk_se@2:

; 477  : 
; 478  : 		//! send the command
; 479  : 		flpydsk_send_command (FDC_CMD_SEEK);

	xor	esi, esi
$LL11@flpydsk_se@2:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN41@flpydsk_se@2
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL11@flpydsk_se@2

; 486  : 
; 487  : 		//! found the cylinder?
; 488  : 		if ( cyl0 == cyl)

	jmp	SHORT $LN9@flpydsk_se@2
$LN41@flpydsk_se@2:

; 477  : 
; 478  : 		//! send the command
; 479  : 		flpydsk_send_command (FDC_CMD_SEEK);

	push	15					; 0000000fH
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN9@flpydsk_se@2:

; 480  : 		flpydsk_send_command ( (head) << 2 | _CurrentDrive);

	mov	al, bl
	or	al, BYTE PTR __CurrentDrive
	xor	esi, esi
	mov	BYTE PTR $T3324[esp+28], al
	npad	5
$LL19@flpydsk_se@2:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN42@flpydsk_se@2
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL19@flpydsk_se@2

; 486  : 
; 487  : 		//! found the cylinder?
; 488  : 		if ( cyl0 == cyl)

	jmp	SHORT $LN17@flpydsk_se@2
$LN42@flpydsk_se@2:

; 480  : 		flpydsk_send_command ( (head) << 2 | _CurrentDrive);

	mov	ecx, DWORD PTR $T3324[esp+28]
	push	ecx
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
$LN17@flpydsk_se@2:

; 481  : 		flpydsk_send_command (cyl);

	xor	esi, esi
$LL27@flpydsk_se@2:
	push	1012					; 000003f4H
	call	?inportb@@YAEG@Z			; inportb
	add	esp, 4
	test	al, al
	js	SHORT $LN43@flpydsk_se@2
	inc	esi
	cmp	esi, 500				; 000001f4H
	jl	SHORT $LL27@flpydsk_se@2

; 486  : 
; 487  : 		//! found the cylinder?
; 488  : 		if ( cyl0 == cyl)

	jmp	SHORT $LL33@flpydsk_se@2
$LN43@flpydsk_se@2:

; 481  : 		flpydsk_send_command (cyl);

	push	ebp
	push	1013					; 000003f5H
	call	?outportb@@YAXGE@Z			; outportb
	add	esp, 8
	npad	6

; 482  : 
; 483  : 		//! wait for the results phase IRQ
; 484  : 		flpydsk_wait_irq ();

$LL33@flpydsk_se@2:
	mov	dl, BYTE PTR __FloppyDiskIRQ
	test	dl, dl
	je	SHORT $LL33@flpydsk_se@2

; 485  : 		flpydsk_check_int (&st0,&cyl0);

	lea	eax, DWORD PTR _cyl0$[esp+28]
	push	eax
	lea	ecx, DWORD PTR _st0$[esp+32]
	push	ecx
	mov	BYTE PTR __FloppyDiskIRQ, 0
	call	?flpydsk_check_int@@YAXPAI0@Z		; flpydsk_check_int
	add	esp, 8

; 486  : 
; 487  : 		//! found the cylinder?
; 488  : 		if ( cyl0 == cyl)

	cmp	DWORD PTR _cyl0$[esp+28], ebp
	je	SHORT $LN44@flpydsk_se@2

; 475  : 
; 476  : 	for (int i = 0; i < 10; i++ ) {

	inc	edi
	cmp	edi, 10					; 0000000aH
	jl	$LL51@flpydsk_se@2

; 490  : 	}
; 491  : 
; 492  : 	return -1;

	pop	esi
	pop	edi
	pop	ebp
	or	eax, -1
	pop	ebx

; 493  : }

	add	esp, 12					; 0000000cH
	ret	0
$LN44@flpydsk_se@2:
	pop	esi
	pop	edi
	pop	ebp

; 489  : 			return 0;

	xor	eax, eax
	pop	ebx

; 493  : }

	add	esp, 12					; 0000000cH
	ret	0
?flpydsk_seek@@YAHII@Z ENDP				; flpydsk_seek
_TEXT	ENDS
PUBLIC	?flpydsk_lba_to_chs@@YAXHPAH00@Z		; flpydsk_lba_to_chs
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_lba$ = 8						; size = 4
_head$ = 12						; size = 4
_track$ = 16						; size = 4
_sector$ = 20						; size = 4
?flpydsk_lba_to_chs@@YAXHPAH00@Z PROC			; flpydsk_lba_to_chs

; 501  : 
; 502  :    *head = ( lba % ( FLPY_SECTORS_PER_TRACK * 2 ) ) / ( FLPY_SECTORS_PER_TRACK );

	mov	ecx, DWORD PTR _lba$[esp-4]
	mov	eax, 954437177				; 38e38e39H
	imul	ecx
	sar	edx, 3
	push	esi
	mov	esi, edx
	shr	esi, 31					; 0000001fH
	add	esi, edx
	lea	eax, DWORD PTR [esi+esi*8]
	add	eax, eax
	add	eax, eax
	mov	edx, ecx
	sub	edx, eax
	mov	eax, 954437177				; 38e38e39H
	imul	edx
	sar	edx, 2
	mov	eax, edx
	shr	eax, 31					; 0000001fH
	add	eax, edx
	mov	edx, DWORD PTR _head$[esp]
	mov	DWORD PTR [edx], eax

; 503  :    *track = lba / ( FLPY_SECTORS_PER_TRACK * 2 );

	mov	eax, DWORD PTR _track$[esp]
	mov	DWORD PTR [eax], esi

; 504  :    *sector = lba % FLPY_SECTORS_PER_TRACK + 1;

	mov	eax, 954437177				; 38e38e39H
	imul	ecx
	sar	edx, 2
	mov	eax, edx
	shr	eax, 31					; 0000001fH
	add	eax, edx
	lea	edx, DWORD PTR [eax+eax*8]
	mov	eax, DWORD PTR _sector$[esp]
	add	edx, edx
	sub	ecx, edx
	inc	ecx
	mov	DWORD PTR [eax], ecx
	pop	esi

; 505  : }

	ret	0
?flpydsk_lba_to_chs@@YAXHPAH00@Z ENDP			; flpydsk_lba_to_chs
_TEXT	ENDS
PUBLIC	?flpydsk_install@@YAXH@Z			; flpydsk_install
EXTRN	?setvect@@YAXHA6AXXZ@Z:PROC			; setvect
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_irq$ = 8						; size = 4
?flpydsk_install@@YAXH@Z PROC				; flpydsk_install

; 509  : 
; 510  : 	//! install irq handler
; 511  : 	setvect (irq, i86_flpy_irq);

	mov	eax, DWORD PTR _irq$[esp-4]
	push	OFFSET ?i86_flpy_irq@@YAXXZ		; i86_flpy_irq
	push	eax
	call	?setvect@@YAXHA6AXXZ@Z			; setvect

; 512  : 
; 513  : 	//! initialize the DMA for FDC
; 514  : 	flpydsk_initialize_dma ();

	call	?flpydsk_initialize_dma@@YAXXZ		; flpydsk_initialize_dma

; 515  : 
; 516  : 	//! reset the fdc
; 517  : 	flpydsk_reset ();

	call	?flpydsk_reset@@YAXXZ			; flpydsk_reset

; 518  : 
; 519  : 	//! set drive information
; 520  : 	flpydsk_drive_data (13, 1, 0xf, true);

	push	1
	push	15					; 0000000fH
	push	1
	push	13					; 0000000dH
	call	?flpydsk_drive_data@@YAXIII_N@Z		; flpydsk_drive_data
	add	esp, 24					; 00000018H

; 521  : }

	ret	0
?flpydsk_install@@YAXH@Z ENDP				; flpydsk_install
_TEXT	ENDS
PUBLIC	?flpydsk_set_working_drive@@YAXE@Z		; flpydsk_set_working_drive
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_drive$ = 8						; size = 1
?flpydsk_set_working_drive@@YAXE@Z PROC			; flpydsk_set_working_drive

; 525  : 
; 526  : 	if (drive < 4)

	mov	al, BYTE PTR _drive$[esp-4]
	cmp	al, 4
	jae	SHORT $LN1@flpydsk_se@3

; 527  : 		_CurrentDrive = drive;

	mov	BYTE PTR __CurrentDrive, al
$LN1@flpydsk_se@3:

; 528  : }

	ret	0
?flpydsk_set_working_drive@@YAXE@Z ENDP			; flpydsk_set_working_drive
_TEXT	ENDS
PUBLIC	?flpydsk_get_working_drive@@YAEXZ		; flpydsk_get_working_drive
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?flpydsk_get_working_drive@@YAEXZ PROC			; flpydsk_get_working_drive

; 532  : 
; 533  : 	return _CurrentDrive;

	mov	al, BYTE PTR __CurrentDrive

; 534  : }

	ret	0
?flpydsk_get_working_drive@@YAEXZ ENDP			; flpydsk_get_working_drive
_TEXT	ENDS
PUBLIC	?flpydsk_read_sector@@YAPAEH@Z			; flpydsk_read_sector
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
tv170 = -4						; size = 4
_sectorLBA$ = 8						; size = 4
?flpydsk_read_sector@@YAPAEH@Z PROC			; flpydsk_read_sector

; 537  : uint8_t* flpydsk_read_sector (int sectorLBA) {

	push	ecx
	push	ebx

; 538  : 
; 539  : 	if (_CurrentDrive >= 4)

	mov	bl, BYTE PTR __CurrentDrive
	cmp	bl, 4
	jb	SHORT $LN2@flpydsk_re@4

; 540  : 		return 0;

	xor	eax, eax
	pop	ebx

; 557  : }

	pop	ecx
	ret	0
$LN2@flpydsk_re@4:

; 541  : 
; 542  : 	//! convert LBA sector to CHS
; 543  : 	int head=0, track=0, sector=1;
; 544  : 	flpydsk_lba_to_chs (sectorLBA, &head, &track, &sector);

	mov	ecx, DWORD PTR _sectorLBA$[esp+4]
	mov	eax, 954437177				; 38e38e39H
	imul	ecx
	sar	edx, 3
	push	ebp
	push	esi
	mov	esi, edx
	shr	esi, 31					; 0000001fH
	add	esi, edx
	lea	eax, DWORD PTR [esi+esi*8]
	add	eax, eax
	add	eax, eax
	mov	edx, ecx
	sub	edx, eax
	mov	eax, 954437177				; 38e38e39H
	imul	edx
	sar	edx, 2
	push	edi
	mov	edi, edx
	shr	edi, 31					; 0000001fH
	add	edi, edx
	mov	eax, 954437177				; 38e38e39H
	imul	ecx
	sar	edx, 2
	mov	eax, edx
	shr	eax, 31					; 0000001fH
	add	eax, edx
	lea	edx, DWORD PTR [eax+eax*8]
	add	edx, edx
	sub	ecx, edx
	lea	ebp, DWORD PTR [ecx+1]

; 545  : 
; 546  : 	//! turn motor on and seek to track
; 547  : 	flpydsk_control_motor (true);

	cmp	bl, 3
	ja	SHORT $LN37@flpydsk_re@4
	movzx	ecx, bl
	xor	eax, eax
	cmp	ecx, 3
	ja	SHORT $LN13@flpydsk_re@4
	jmp	DWORD PTR $LN41@flpydsk_re@4[ecx*4]
$LN12@flpydsk_re@4:
	mov	eax, 16					; 00000010H
	jmp	SHORT $LN13@flpydsk_re@4
$LN11@flpydsk_re@4:
	mov	eax, 32					; 00000020H
	jmp	SHORT $LN13@flpydsk_re@4
$LN10@flpydsk_re@4:
	mov	eax, 64					; 00000040H
	jmp	SHORT $LN13@flpydsk_re@4
$LN9@flpydsk_re@4:
	mov	eax, 128				; 00000080H
$LN13@flpydsk_re@4:
	or	bl, al
	or	bl, 12					; 0000000cH
	movzx	eax, bl
	push	eax
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	push	20					; 00000014H
	call	?sleep@@YAXH@Z				; sleep
	add	esp, 12					; 0000000cH
$LN37@flpydsk_re@4:

; 548  : 	if (flpydsk_seek (track, head) != 0)

	push	edi
	push	esi
	call	?flpydsk_seek@@YAHII@Z			; flpydsk_seek
	add	esp, 8
	test	eax, eax
	je	SHORT $LN1@flpydsk_re@4

; 549  : 		return 0;

	pop	edi
	pop	esi
	pop	ebp
	xor	eax, eax
	pop	ebx

; 557  : }

	pop	ecx
	ret	0
$LN1@flpydsk_re@4:

; 550  : 
; 551  : 	//! read sector and turn motor off
; 552  : 	flpydsk_read_sector_imp (head, track, sector);

	push	ebp
	push	esi
	push	edi
	call	?flpydsk_read_sector_imp@@YAXEEE@Z	; flpydsk_read_sector_imp

; 553  : 	flpydsk_control_motor (false);

	mov	al, BYTE PTR __CurrentDrive
	add	esp, 12					; 0000000cH
	cmp	al, 3
	ja	SHORT $LN31@flpydsk_re@4
	push	4
	push	1010					; 000003f2H
	call	?outportb@@YAXGE@Z			; outportb
	push	20					; 00000014H
	call	?sleep@@YAXH@Z				; sleep
	add	esp, 12					; 0000000cH
$LN31@flpydsk_re@4:

; 554  : 
; 555  : 	//! warning: this is a bit hackish
; 556  : 	return (uint8_t*) DMA_BUFFER;

	pop	edi
	pop	esi
	pop	ebp
	mov	eax, 4096				; 00001000H
	pop	ebx

; 557  : }

	pop	ecx
	ret	0
	npad	3
$LN41@flpydsk_re@4:
	DD	$LN12@flpydsk_re@4
	DD	$LN11@flpydsk_re@4
	DD	$LN10@flpydsk_re@4
	DD	$LN9@flpydsk_re@4
?flpydsk_read_sector@@YAPAEH@Z ENDP			; flpydsk_read_sector
_TEXT	ENDS
END
